#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This file is execfile()d with the current directory set to its
containing dir.

Note that not all possible configuration values are present in this
autogenerated file.

All configuration values have a default; values that are commented out
serve to show the default.

If extensions (or modules to document with autodoc) are in another directory,
add these directories to sys.path here. If the directory is relative to the
documentation root, use os.path.abspath to make it absolute, like shown here.

http://www.sphinx-doc.org/en/stable/config.html
http://www.sphinx-doc.org/en/stable/extensions.html#extensions
http://www.sphinx-doc.org/en/stable/ext/thirdparty.html
"""

import os
import sys

sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    'sphinxcontrib.tikz',
]

templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# General information about the project.
project = 'TU-A1150 - Filosofia ja systeemiajattelu, 18.01.2017-31.03.2017'
copyright = '2017, Jaan Tollander de Balsch'
author = 'Jaan Tollander de Balsch'
institute = 'Aalto University'
student_number = '452056'

version = ''
release = ''
language = 'en'
today_fmt = '%Y-%m-%d'

pygments_style = 'sphinx'
todo_include_todos = False

# -- Graphviz --------------------------------------------------------

extensions += ['sphinx.ext.graphviz']
graphviz_dot = 'dot'
graphviz_dot_args = []
graphviz_output_format = 'png'  # svg


# -- Napoleon --------------------------------------------------------
# http://www.sphinx-doc.org/en/stable/ext/napoleon.html


# napoleon_google_docstring = True
# napoleon_numpy_docstring = True
# napoleon_include_init_with_doc = False
# napoleon_include_private_with_doc = False
# napoleon_include_special_with_doc = True
# napoleon_use_admonition_for_examples = False
# napoleon_use_admonition_for_notes = False
# napoleon_use_admonition_for_references = False
# napoleon_use_ivar = False
# napoleon_use_param = True
# napoleon_use_rtype = True


# -- Sphinxcontrib --------------------------------------------------------

extensions += [
    # 'sphinxcontrib.programoutput',
    # 'sphinxcontrib.bibtex',
    # 'sphinxcontrib.youtube',
]

# -- Options for HTML output ----------------------------------------------

try:
    import sphinx_rtd_theme

    html_theme = "sphinx_rtd_theme"
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
    html_theme_options = {}
except ImportError() as e:
    html_theme = 'alabaster'
    html_theme_options = {}

html_static_path = ['_static']

# -- Options for HTMLHelp output ------------------------------------------

htmlhelp_basename = 'ArticleSummarydoc'

# -- Options for LaTeX output ---------------------------------------------

preamble = r"""
\usepackage{amsfonts}
\usepackage{parskip}
\usepackage{microtype}
\usepackage{tikz}
"""

mystyle = 'customtitle'
preamble += '\n'
preamble += r'\usepackage{%s}' % mystyle

preamble += '\n'
preamble += r'\institute{%s}' % institute

institute = 'Aalto University'
preamble += '\n'
preamble += r'\project{%s}' % project

latex_engine = 'pdflatex'
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'preamble': preamble,
    'figure_align': 'htbp',
}

# ('source', 'target', 'title', 'author', 'documentclass')
latex_documents = []


def tex_file(*args):
    from boltons.strutils import slugify
    return slugify(' '.join(args)) + '.tex'


# Summary
latex_documents.append((
    'summary/index', tex_file('summary', student_number),
    'Referaatti', author, 'report'
))
# latex_logo = '_static/Philosophy.png'

# Oppimiskeskustelu
authors = [
    (author, student_number),
    ('Henri Ailas', '345260'),
    ('Jarmo Romo', '298375'),
    ('Anssi Karppinen', '425533'),
    ('Topias Härmä', '429089'),
]
latex_documents.append((
    'oppimiskeskustelu/index',
    tex_file(*(['raportti'] + [numb for auth, numb in authors])),
    'Räjähdysvoimaisen Oppimiskeskustelun Raportti',
    r'\\'.join((', '.join(details) for details in authors)),
    'report'
))
# latex_logo = '_static/pulp-fiction-duo.jpg'

# Reflektioessee
latex_documents.append((
    'reflektioessee/index',
    tex_file('reflektioessee', student_number),
    'Landscape of my Life', author, 'report'
))
latex_logo = '_static/limitless-movie-review-1.png'


latex_show_urls = 'footnote'
latex_additional_files = [
    mystyle + '.sty'
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc,
     'articlesummary',
     'Article Summary Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc,
     'ArticleSummary',
     'Article Summary Documentation',
     author,
     'ArticleSummary',
     'One line description of project.',
     'Miscellaneous'),
]
